AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for Aurora MySQL backup.

Parameters:
  ProjectName:
    Type: String
    Default: hs-backup-aurora
  EcrImageUri:
    Description: ECR image URI
    Type: String
  CidrBlockVPC:
    Type: String
    Default: 172.16.0.0/16
  CidrBlockPublicSubnetA:
    Type: String
    Default: 172.16.0.0/24
  CidrBlockPrivateSubnetA:
    Type: String
    Default: 172.16.10.0/24
  CidrBlockPrivateSubnetC:
    Type: String
    Default: 172.16.20.0/24
  MasterUsername:
    Type: String
  MasterUserPassword:
    Type: String

Resources:
  # VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-vpc.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        CidrBlockVPC: !Ref CidrBlockVPC
        CidrBlockPublicSubnetA: !Ref CidrBlockPublicSubnetA
        CidrBlockPrivateSubnetA: !Ref CidrBlockPrivateSubnetA
        CidrBlockPrivateSubnetC: !Ref CidrBlockPrivateSubnetC
  # セキュリティグループ
  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-security-group.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        VPC: !GetAtt VPC.Outputs.VPC
        CidrBlockPublicSubnetA: !Ref CidrBlockPublicSubnetA
  # VPCエンドポイント
  VPCEndpoint:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-endpoint.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPC
        PublicSubnetA: !GetAtt VPC.Outputs.PublicSubnetA
        VPCEndpointSecurityGroup: !GetAtt SecurityGroup.Outputs.VPCEndpointSecurityGroup
        RouteTablePublic: !GetAtt VPC.Outputs.RouteTablePublic
  # 踏み台EC2
  BastionEC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-bastion.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        PublicSubnetSecurityGroup: !GetAtt SecurityGroup.Outputs.PublicSubnetSecurityGroup
        PublicSubnetA: !GetAtt VPC.Outputs.PublicSubnetA
  # S3
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-s3.yaml
      Parameters:
        ProjectName: !Ref ProjectName
  # Aurora
  Aurora:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-aurora.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        PrivateSubnetA: !GetAtt VPC.Outputs.PrivateSubnetA
        PrivateSubnetC: !GetAtt VPC.Outputs.PrivateSubnetC
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterUserPassword
        PrivateSubnetSecurityGroup: !GetAtt SecurityGroup.Outputs.PrivateSubnetSecurityGroup
  # Lambda
  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cf-template-02-lambda.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EcrImageUri: !Ref EcrImageUri
        PublicSubnetSecurityGroup: !GetAtt SecurityGroup.Outputs.PublicSubnetSecurityGroup
        PublicSubnetA: !GetAtt VPC.Outputs.PublicSubnetA
        S3Bucket: !GetAtt S3.Outputs.S3Bucket
        SecretId: !GetAtt Aurora.Outputs.SecretId
