version: "3.9"
services:
  lambda:
    build: ./
    ports:
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      S3_BUCKET_NAME: hs-backup-aurora-local-bucket
      SECRETS_NAME: hs-backup-aurora-local-secrets
      TZ: Asia/Tokyo
    volumes:
      - ./src/bootstrap:/var/runtime/bootstrap
      - ./src/function.sh:/var/task/function.sh
  db:
    image: mysql:5.7.41
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rirazou
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
volumes:
  db:
